version: '3.9'
services:
  db:
    image: postgres:15.3
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}
    restart: always

  app:
    build: .
    depends_on:
      - db
    restart: always

volumes:
  db-data: