version: '3.9'
services:
  db:
    image: postgres:15.4
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    restart: always

  app:
    build: .
    depends_on:
      - db
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    restart: always

volumes:
  db-data: