version: '3.9'
services:
  db_test:
    image: postgres:15.4
    env_file:
      - configs/test.env
    expose:
      - 5432
    restart: always

  app_test:
    build: .
    depends_on:
      - db_test
    environment:
      - ENV=test
    ports:
      - 8081:8081
    restart: always
