version: '3.9'
services:
  db:
    image: postgres:15.4
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - configs/dev.env
    expose:
      - 5432
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    environment:
      - ENV=dev
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  db-data: