// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	models "segmentify/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SegmentCreator is an autogenerated mock type for the SegmentCreator type
type SegmentCreator struct {
	mock.Mock
}

// CreateSegment provides a mock function with given fields: _a0
func (_m *SegmentCreator) CreateSegment(_a0 models.Segment) (models.Segment, error) {
	ret := _m.Called(_a0)

	var r0 models.Segment
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Segment) (models.Segment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(models.Segment) models.Segment); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Segment)
	}

	if rf, ok := ret.Get(1).(func(models.Segment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSegmentCreator creates a new instance of SegmentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSegmentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SegmentCreator {
	mock := &SegmentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
